### ISSUE TITLE
pobranie listy aukcji

### ISSUE THREAD

**Issue by pklimczu** [dominikj/PKRY#1]
oknoglowne.cpp
=>
Metoda void OknoGlowne::on_listWidget_itemDoubleClicked(QListWidgetItem *item)
=>
pierwsze wywołanie instrukcji warunkowej (linijka 115)
=>
zastąpić czymś w rodzaju zapelnij_liste_aukcji(_sterownik.listaAukcji())

zwraca QString według ustalonego formatu

**Comment by dominikj** [comment]
Udostępniam: QString pobierzAukcje()

**Comment by pklimczu** [comment]
Po kliknięciu ODŚWIEŻ...:
"Program nieoczekiwanie przerwał pracę."
Domyślam się, że to z powodu braku łączności.  W którym miejscu powinien być jakiś try i catch?

**Comment by pklimczu** [comment]
Zrobione.
