### ISSUE TITLE
wybor zwycięzcy

### ISSUE THREAD

**Issue by pklimczu** [dominikj/PKRY#4]
Musimy rozstrzygnąć, czy uda się zrobić stały nasłuch na wiadomość od GAPa, czy będzie pobierane "na żądanie". W pierwszym wypadku okno klasy WybierzZwyciezce musi być tworzone poza OknemGlownym, tj. np. w bazie - i na podstawie żądania sterownika wyrzucić okno dla użytkownika (pomijając to, co aktualnie robi - po prostu stworzyć obiekt, uzupełnić metodą wez_dane_aukcji i wyświetlić). Wówczas możemy dać tej klasie dostęp do sterownika (ja nie umiem tego przekazać, tj. referencji) i obsługujemy to poza wszystkim, jako trzecie samodzielne okienko.
W drugim wypadku, przygotuj proszę dwie metody w sterowniku, jedna w stylu "sprawdź_czy_można_wybrać_zwyciezce" czy coś takiego, żeby po naciśnieciu guzika klient łączył się z GAPem i patrzył, czy to już etap wyboru zwycięzcy -> a jeśli tak, to żeby dostawał odpowiedniego QStringa w zwrocie (dalej obsługą już się zajmę).
Natomiast druga metoda w stylu _sterownik.zwyciezca(QString nr_zwyciezy, QString nr_ofer_wzietych_pod_uwage) - albo jeden QString, jak Ci wygodniej, to się najwyżej sklei/rozklei u klienta albo na GAPie. To będzie metoda, która będzie wywoływana po wybraniu przez firmę zwycięzcy i kliknięciu przycisku "Wybierz". Dokoduję co trzeba, dobrze by jednak było żeby ta metoda zwracała też info o powodzeniu lub jego braku.

**Comment by dominikj** [comment]
Udostępniłem nowy interfejs w klasie sterownik:
OczekujZwyciezcy \* czekajNaZwyciezce();
Zwraca wskaźnik na obiekt klasy OczekujZwyciezcy, który, gdy odbierze jakieś dane od GAP emituje sygnał: void alertZwyciezca(QString zwyciezca) dlatego złap go sobie. Tak na prawdę wystarczyłby sygnał zrobić w klasie sterownik, bez jakiś nowych klas, ale może trzeba będzie jakoś przenosić to do wątku czy coś, więc zostawiłem sobie taką furtkę.

**Comment by pklimczu** [comment]
Imho zrobione, może nie najładniej, ale powinno działać.
