### ISSUE TITLE
Logowanie z błędnymi danymi - awaria serwera

### ISSUE THREAD

**Issue by pklimczu** [dominikj/PKRY#9]
Pewnie to wziąłeś pod uwagę w dalszej perspektywie - ale podanie na przykład loginu "Wojtek" i hasła "takie" powoduje:

```
Uruchamianie /home/kuczmil/Projekt/eAukcja/PKRY/build-eAukcjaSerwer-Desktop_Qt_5_5_1_GCC_64bit-Debug/eAukcjaSerwer...
Nasłuchuje
Użytkownik:  1083605458  nawiązał połączenie
Odebrano dane od użytkownika: 1083605458
terminate called after throwing an instance of 'Botan::Decoding_Error'
  what():  Decoding error: PK_Decryptor_EME: Input is invalid
Program nieoczekiwanie przerwał pracę.
/home/kuczmil/Projekt/eAukcja/PKRY/build-eAukcjaSerwer-Desktop_Qt_5_5_1_GCC_64bit-Debug/eAukcjaSerwer zakończył pracę błędem
```

**Comment by pklimczu** [comment]
Ogólnie zrobiłem pulla tego co jest i łyknął. Zrobiłem tak jak w issue #8, ale nawet po podaniu loginu i hasła takiego jak w pliku users.txt pojawia się w/w błąd :(

**Comment by dominikj** [comment]
Chyba gałęzie stały się w jakiś sposób niespójne, bo może masz inną treść podprotokołów, pamiętaj że mergując do siebie preferowane są zmiany w twojej gałęzi, nie z gałęzi "przychodzącej" 
Celem testu załóż sobie lokalną gałąź Dominik (jeśli wcześniej nie robiłeś tego), ustaw śledzenie zdalnej, przejdź na moją gałąź git checkout Dominik i wykonaj git pull. Spróbuj moje skompilować i uruchomić, jeśli działa (bo u mnie tak) to istnieje niespójność w gałęziach. 
Natomiast jeśli już wcześniej bawiłeś się gałęzią Dominik, to przejdź na nią i wykonaj:
git fetch
git reset --hard

**Comment by dominikj** [comment]
Bo ja pobrałem Twoją gałąź i to, co tam masz teraz na serwerze to jakieś niewiadomo co jest. Domyślam się że pullowałeś master i mergowałeś do swojej gałęzi i tutaj może coś się rozjechało.

**Comment by pklimczu** [comment]
Zrobiłem na masterze u siebie:

```
git fetch --all
git reset --hard origin/master
```

Czyli jak rozumiem, wyczyściłem wszystko lokalnie i pobrałem całość stąd. Uruchomiłem qmake`i, przebudowałem - wciąż to samo.

**Comment by pklimczu** [comment]
Na mojej gałęzi nie ma jeszcze serwera :P

**Comment by dominikj** [comment]
A czy przypadkiem serwer nie ma błędnego klucza - plik gapPriv ???!
Bo przyczyny tego błędu są dwie - albo klient przesyła złe dane (np. zaszyfrowane innym kluczem) albo serwer ma zły klucz

**Comment by dominikj** [comment]
Hint: jeśli nie poradzisz sobie z tymi kluczami to najpierw:
1) spróbuj keygenem wygenerować nową parę kluczy - publiczny wrzuć jako gap do klienta, a prywatny jako gapPriv do serwera
2) Jeśli to nie pomoże to wygeneruj jeszcze jedną parę kluczy - prywatny wrzuć do klienta jako skcca, a publiczny jako Wojtek_PKcca do serwera

**Comment by pklimczu** [comment]
Hint naprawił sytuację, zamykam.
